services:
  backend:
    container_name: backend
    #platform: linux/amd64
    build:
      context: . # kommer se allt som finns i rotmappen (där docker-compose filer ligger)
      dockerfile: dockerfiles/backend.dockerfile
    ports: 
      - "8000:8000" # mappar vår host till containern
    image: ${ACR_LOGIN_SERVER}/backend:${IMAGE_TAG:-lastest}

  frontend:
    container_name: frontend
    #platform: linux/amd64
    build:
      context: . 
      dockerfile: dockerfiles/frontend.dockerfile
    ports: 
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000
    image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG:-lastest}
